import { MAIN_PAGE_FILTER } from '@/lib/sanity/mainPageFilter'
import { MAIN_PAGE_SECTIONS_QUERY } from '@/lib/sanity/mainPageSectionsQuery'

/** GROQ for `mainPage` singleton — kept separate so client bundles can import `@/lib/sanity` without loading `next-sanity/live`. */
export const MAIN_PAGE_QUERY = `
  *[${MAIN_PAGE_FILTER}][0]{
    title,
    ${MAIN_PAGE_SECTIONS_QUERY}
    eyebrow,
    headline,
    scriptHeadline,
    subtitle,
    heroImage,
    primaryCta{
      text,
      link{
        linkType,
        url,
        reference->{ _type, slug }
      }
    },
    secondaryCta{
      text,
      link{
        linkType,
        url,
        reference->{ _type, slug }
      }
    },
    socialProof,

    featuredReviews[]->{
      _id,
      author,
      label,
      text
    },
    seoConversionSection{
      enabled,
      anchorId,
      eyebrow,
      title,
      intro,
      terms[]{
        termId,
        title,
        subtitle,
        description
      }
    },
    challenges{
      title,
      managerTitle,
      participantTitle,
      collectiveTitle,
      managerChallenges,
      participantChallenges,
      collectiveChallenges,
      conclusion
    },
    nineDaysProgram{
      eyebrow,
      title,
      subtitle,
      habits,
      days,
      testimonials,
      completionSection{
        title,
        description,
        selectedHabits,
        nextCourseInfo,
        buttonText
      },
      faqSection{
        question,
        testimonials
      }
    },
    aboutAndres{
      eyebrow,
      title,
      subtitle,
      quote,
      description,
      tags,
      stats{
        value,
        label
      },
      certificationLink,
      mainImage{
        asset->,
        alt
      },
      overlayImage{
        asset->,
        alt
      },
      overlayImage2{
        asset->,
        alt
      }
    },
    testimonials{
      title,
      subtitle,
      testimonials{
        name,
        role,
        company,
        content,
        rating,
        avatar{
          asset->,
          alt
        }
      },
      buttonText,
      buttonLink
    },
    beforeAfter{
      title,
      subtitle,
      highlightText,
      transformations[]{
        before,
        after
      },
      materialsTitle,
      materialsDescription,
      bookTitle,
      bookDescription,
      resultTitle,
      resultDescription,
      buttonText,
      buttonLink
    },
    finalCTA{
      title,
      subtitle,
      nextGroupInfo,
      spotsInfo,
      supportInfo,
      supportPrefix,
      primaryButtonText,
      primaryButtonLink,
      secondaryButtonText,
      secondaryButtonLink,
      footerText
    },
    grantSection{
      eyebrow,
      percentLabel,
      title,
      highlightedTitle,
      description,
      ctaText,
      ctaLink,
      responseText,
      infoPrefix,
      infoHighlight,
      infoSuffix,
      steps[]{
        title,
        description,
        highlight
      }
    },
    photoMarquee{
      title,
      subtitle,
      gradientFrom,
      gradientTo,
      photos[]{
        image{
          asset->,
          alt
        },
        caption
      }
    },
    pricingSection{
      title,
      subtitle,
      popularBadgeText,
      ctaText,
      footerNotice,
      supportNotePrefix,
      supportNoteHighlight,
      tiers[]{
        name,
        price,
        description,
        features,
        isPopular
      },
      corporateTitle,
      corporateSubtitle,
      corporatePrice,
      corporatePricePrefix,
      corporatePriceTaxLabel,
      corporatePriceSuffix,
      corporateFeatures,
      corporateCtaText,
      corporateBadgeText
    },
    seo{
      metaTitle,
      metaDescription,
      metaKeywords,
      ogImage{
        asset->,
        alt
      }
    },
    quiz{
      title,
      eyebrow,
      introTopLine,
      introAccentLine,
      introDescription,
      questions[]{
        question,
        options[]{
          text,
          points
        }
      },
      results[]{
        minScore,
        title,
        description,
        ctaLink
      }
    },
    helpFormTeaser{
      enabled,
      eyebrow,
      title,
      description,
      buttonText,
      formUrl,
      image
    },
    nineDaysMini{
      eyebrow,
      mainHeading,
      mainTitle,
      italicTitle,
      subtitle,
      greenButtonText,
      greenButtonLink,
      whiteButtonText,
      whiteButtonLink,
      overviewLabel,
      dayPickerLabel,
      progressLabel,
      dayBadgePrefix,
      habitLabel,
      planCtaPrefix,
      planCtaLinkText,
      planCtaLinkUrl,
      planButtonText,
      planButtonLink,
      oppepaevad[]->{
        dayNumber,
        tag,
        title,
        habitsFocus,
        companyPain,
        shortSolution
      },
      programDays{
        day1{ dayNumber, title, subtitle, habit, typeLabel, companyPainTitle, companyPain, shortSolution, participantWins, companyWins },
        day2{ dayNumber, title, subtitle, habit, typeLabel, companyPainTitle, companyPain, shortSolution, participantWins, companyWins },
        day3{ dayNumber, title, subtitle, habit, typeLabel, companyPainTitle, companyPain, shortSolution, participantWins, companyWins },
        day4{ dayNumber, title, subtitle, habit, typeLabel, companyPainTitle, companyPain, shortSolution, participantWins, companyWins },
        day5{ dayNumber, title, subtitle, habit, typeLabel, companyPainTitle, companyPain, shortSolution, participantWins, companyWins },
        day6{ dayNumber, title, subtitle, habit, typeLabel, companyPainTitle, companyPain, shortSolution, participantWins, companyWins },
        day7{ dayNumber, title, subtitle, habit, typeLabel, companyPainTitle, companyPain, shortSolution, participantWins, companyWins },
        day8{ dayNumber, title, subtitle, habit, typeLabel, companyPainTitle, companyPain, shortSolution, participantWins, companyWins },
        day9{ dayNumber, title, subtitle, habit, typeLabel, companyPainTitle, companyPain, shortSolution, participantWins, companyWins }
      },
      days[]{
        dayNumber,
        title,
        subtitle,
        habit,
        typeLabel,
        companyPainTitle,
        companyPain,
        shortSolution,
        participantWins,
        companyWins
      },
      leadForm{
        introTitle,
        introText,
        emailLabel,
        emailPlaceholder,
        submitText,
        submitPendingText,
        closeText,
        successTitle,
        successText,
        readMoreLinkText
      },
      faqSection{
        question,
        testimonials[]{
          quote,
          author
        }
      }
    }
  }
`
