/**
 * Legacy top-level fields duplicated by page builder `sections[]`.
 * Safe to unset once `sections` is populated — the site reads block data first.
 */
export const PAGE_LEGACY_FIELDS = {
  mainPage: [
    'eyebrow',
    'headline',
    'scriptHeadline',
    'subtitle',
    'description',
    'primaryCta',
    'secondaryCta',
    'socialProof',
    'stats',
    'features',
    'featuredReviews',
    'seoConversionSection',
    'challenges',
    'nineDaysProgram',
    'aboutAndres',
    'beforeAfter',
    'grantSection',
    'photoMarquee',
    'pricingSection',
    'finalCTA',
    'quiz',
    'helpFormTeaser',
    'nineDaysMini',
    'partnersTitle',
    'partners',
    'testimonials',
  ],
  koolitusPage: [
    'hero',
    'audienceSection',
    'nineDaysProgram',
    'featuresSection',
    'buildingsSection',
    'leanHouseSection',
    'investmentSection',
    'leadFormTeaser',
    'cohortsSection',
    'certificateSection',
    'pricesSection',
    'featuredReviews',
    'testimonialsSection',
    'kkk',
    'kkkDocument',
    'ctaSection',
    'contactSection',
    'finalCTA',
  ],
  opstarProfit: [
    'featuredReviews',
    'orbitBlockRef',
    'comparisonPartnerLogos',
    'hero',
    'contentSections',
    'comparison',
    'kolmSammast',
    'framework',
    'eightComponents',
    'leanVsOpstar',
    'meodetavadTulemused',
    'cases',
    'arvamused',
    'kkk',
    'cta',
  ],
  aboutPage: [
    'featuredReviews',
    'hero',
    'quoteSection',
    'aboutSection',
    'experienceSection',
    'guaranteeSection',
    'ctaSection',
    'keyAchievements',
    'worldManufacturingVisits',
    'expertise',
    'testimonialsSection',
    'testimonials',
    'services',
    'kkkDocument',
    'kkk',
    'contactSection',
  ],
  kontaktPage: [
    'richText',
    'hero',
    'quickContact',
    'messageForm',
    'andresBlock',
    'opstarBlock',
    'servicesSection',
    'legalNote',
  ],
}

/** Fields kept on every page document regardless of migration state. */
export const PAGE_KEEP_FIELDS = new Set(['title', 'sections', 'seo'])

/**
 * Do not strip a legacy field until the matching builder block exists in sections[].
 * Prevents blank heroes/sections after strip-legacy.
 */
export const LEGACY_FIELD_REQUIRES_SECTION_BLOCK = {
  koolitusPage: {
    hero: 'marketingSplitHeroBlock',
    nineDaysProgram: 'koolitusNineDaysProgramBlock',
    investmentSection: 'koolitusInvestmentBlock',
    featuresSection: 'koolitusFeaturesBlock',
    leanHouseSection: 'koolitusLeanHouseBlock',
    cohortsSection: 'koolitusCohortsBlock',
    certificateSection: 'koolitusCertificateBlock',
  },
  mainPage: {
    quiz: 'homeQuizBandBlock',
    nineDaysMini: 'homeNineDaysMiniBlock',
    aboutAndres: 'homeAboutBlock',
    grantSection: 'homeGrantBlock',
    photoMarquee: 'homePhotoMarqueeBlock',
    beforeAfter: 'homeBeforeAfterBlock',
    pricingSection: 'homePricingBlock',
    finalCTA: 'homeFinalCtaBlock',
  },
}